# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='salon.Town'),
        ),
        migrations.AddField(
            model_name='profile',
            name='townpin',
            field=models.BooleanField(default=False),
        ),
    ]
